export const formSendType = {
  SMS: 'SMS',
  MAIL: 'MAIL',
  SNAIL_MAIL: 'SNAIL_MAIL',
  DIGITAL_MAIL: 'DIGITAL_MAIL',
  EMAIL: 'EMAIL',
  LETTER: 'LETTER',
  REK_MAIL: 'REK-MAIL',
  DIGITAL_REGISTERED_LETTER: 'DIGITAL_REGISTERED_LETTER',
} as const;
