name: Lint

permissions:
  contents: read

on: [workflow_dispatch, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [frontend, admin]
    name: ESLint (${{ matrix.app }})
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ${{ matrix.app }}/yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent --network-timeout 1000000

      - name: Run ESLint
        run: yarn lint
